name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name : Clone down
        uses: actions/checkout@v2
        run: bash ci/build-app.sh